import std/terminal
import std/os
import std/[strutils, strformat]

from utils import cleanWorkingDir, printName

from compiler import compiler

proc variablesCreator*(x: int) = 
    printName()
    var appDirectory = getAppDir()
    setCurrentDir(appDirectory / "NullRAT")
    
    if x != 1:
        stdout.styledWriteLine({styleBright}, "  >> Variables Creator <<")
        if fileExists("Variables.py"):
            stdout.styledWriteLine(fgGreen, {styleBright}, "\n[INFO] Existing Variables file discovered!")
            stdout.styledWriteLine(fgCyan, {styleBright}, "\nStored information\n------------------")
            let EnF = readFile("Variables.py")
            stdout.styledWriteLine(fgCyan, {styleBright}, EnF)
            stdout.styledWriteLine({styleBright}, "\nIs this information correct? (Y/n)")
            var input: char = getch()
            if input == 'N' or input == 'n':
                echo "- Information marked incorrect! Continuing..."
                sleep(1000)
                printName()
            elif input == 'Q' or input == 'q': return 
            else:
                stdout.styledWriteLine(fgGreen, {styleBright}, "- Information marked correct. Preserving...")
                sleep(1000)
                if compiler() == 0:
                    return 

    stdout.styledWriteLine(fgWhite, {styleBright}, "----------------\nTo know how to obtain the variables,\nCheck 'Getting Variables.md' in NullRAT Github\n----------------")
    stdout.styledWriteLine(fgWhite, {styleBright}, "\n[1] Please enter the Discord bot token: ")
    var token = readLine(stdin);
    stdout.styledWriteLine(fgWhite, {styleBright}, "[2] Please enter the Server ID: ")
    var serverID = readLine(stdin)
    stdout.styledWriteLine(fgWhite, {styleBright}, "[3] Please enter the Notification channel ID: ")
    var notificationID = readLine(stdin)
        
    let lines = [
        fmt"bot_token = ""{token}""",
        "notification_channel = " & notificationID,
        "server_ids = [" & serverID & "]"
    ]
    
    var linesString: string = "# This file was auto-generated by NullRAT Builder. DO NOT EDIT!\n"

    printName()
    stdout.styledWriteLine({styleBright}, "  >> Variables Creator <<")
    echo "\nObtained information:\n---------------------"

    for line in lines:
        if "#" in line: continue
        echo line
        linesString.add("\n"&line)
    echo ""

    stdout.styledWriteLine({styleBright}, "Is this information correct? (Y/n)")
    var input: char = getch()
    if input == 'N' or input == 'n':
        echo "- Aborted! Returning to main menu..."
        sleep(1500)
        variablesCreator(1)
    elif input == 'Q' or input == 'q': return 
    else:
        echo "- Information marked correct. Writing..."
        removeFile("Variables.py")
        
        echo linesString
        let
          fileName = "Variables.py"
          str = linesString
        writeFile(fileName, str)

        stdout.styledWriteLine({styleBright}, "- Written information to disk!")
        echo ""
        stdout.styledWriteLine({styleBright}, "Moving on to compiler...")
        sleep(3000)
        if compiler() == 0:
            return
