@echo off & @color A & @title NullRAT Variables

cls & cd "%~dp0NullRAT"
IF EXIST "Variables.py" (goto fileE) else (goto createF)

:createF
echo   _   _       _ _ _____         _______  __      __        _       _     _           
echo  ^| ^\ ^| ^|     ^| ^| ^|  __ ^\     /^\^|__   __^| ^\ ^\    / /       (_)     ^| ^|   ^| ^|          
echo  ^|  ^\^| ^|_   _^| ^| ^| ^|__) ^|   /  ^\  ^| ^|     ^\ ^\  / /_ _ _ __ _  __ _^| ^|__ ^| ^| ___  ___ 
echo  ^| . ` ^| ^| ^| ^| ^| ^|  _  /   / /^\ ^\ ^| ^|      ^\ ^\/ / _` ^| '__^| ^|/ _` ^| '_ ^\^| ^|/ _ ^\/ __^|
echo  ^| ^|^\  ^| ^|_^| ^| ^| ^| ^| ^\ ^\  / ____ ^\^| ^|       ^\  / (_^| ^| ^|  ^| ^| (_^| ^| ^|_) ^| ^|  __/^\__ ^\
echo  ^|_^| ^\_^|^\__,_^|_^|_^|_^|  ^\_^\/_/    ^\_^\_^|        ^\/ ^\__,_^|_^|  ^|_^|^\__,_^|_.__/^|_^|^\___^|^|___/
echo.
set /p "token=Enter Bot Token: "
if "%token%"=="" (cls & echo [ERROR] Token cannot be empty! & goto createF)
set /p "notification=Enter Notification ID: "
if "%notification%"=="" (cls & echo [ERROR] Notification cannot be empty! & goto createF)
set /p "server=Enter Server ID: "
if "%server%"=="" (cls & echo [ERROR] Server cannot be empty! & goto createF)

echo ^# This file was auto-generated by NullRAT Variables^. DO NOT SHARE^! > Variables.py
echo bot_token = ^"%token%^" >> Variables.py
echo notification_channel = %notification% >> Variables.py
echo server_ids = ^[%server%^] >> Variables.py

echo, & echo All variables properly saved & PAUSE & EXIT

:fileE
echo   _   _       _ _ _____         _______  __      __        _       _     _           
echo  ^| ^\ ^| ^|     ^| ^| ^|  __ ^\     /^\^|__   __^| ^\ ^\    / /       (_)     ^| ^|   ^| ^|          
echo  ^|  ^\^| ^|_   _^| ^| ^| ^|__) ^|   /  ^\  ^| ^|     ^\ ^\  / /_ _ _ __ _  __ _^| ^|__ ^| ^| ___  ___ 
echo  ^| . ` ^| ^| ^| ^| ^| ^|  _  /   / /^\ ^\ ^| ^|      ^\ ^\/ / _` ^| '__^| ^|/ _` ^| '_ ^\^| ^|/ _ ^\/ __^|
echo  ^| ^|^\  ^| ^|_^| ^| ^| ^| ^| ^\ ^\  / ____ ^\^| ^|       ^\  / (_^| ^| ^|  ^| ^| (_^| ^| ^|_) ^| ^|  __/^\__ ^\
echo  ^|_^| ^\_^|^\__,_^|_^|_^|_^|  ^\_^\/_/    ^\_^\_^|        ^\/ ^\__,_^|_^|  ^|_^|^\__,_^|_.__/^|_^|^\___^|^|___/
echo.
echo A pre-existing variables file was detected.
choice /c YN /n /m "Do you want to check its contents? [Y/N]"
if %errorlevel%==2 (cls & goto createF)
if %errorlevel%==1 (goto endd)

:endd
echo. & type Variables.py & echo.
choice /c YN /n /m "Are all these information correct? [Y/N]"
if %errorlevel%==2 (cls & goto createF)
if %errorlevel%==1 (	
	echo. & echo The following information is correct. Closing... 
	timeout /t 2 >nul & exit
)
